repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7  # Use the latest tag from https://github.com/astral-sh/ruff-pre-commit/tags
    hooks:
      # Run the formatter.
      - id: ruff-format  # Optional: auto-formatting like black
      # Run the linter.
      - id: ruff-check
     